const MAIN_MENU_LAYER = 10;
const SETTINGS_LAYER = 9
const PAUSE_LAYER = 8;
const FADE_LAYER = 7;
const DARKNESS_LAYER = 6;
const ITEM_LAYER = 3;
const ENEMY_LAYER = 2;
const PLAYER_LAYER= 2;
const MAP_LAYER = 1;