# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Environment-Setup:

    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        run: |
          echo "$ apt update"
          apt update

          echo "$ apt install python3 -y"
          apt install python3 -y

          echo "$ python3  -V"
          python3 -V


      - name: Check Node Version
        run: |
          echo "$ node -v"
          node -v

      - name: Check NPM Version
        run: |
          echo "$ npm -v"
          npm -v

      - name: Install Selinium Webdriver
        run: |
          echo "$ npm install selenium-webdriver"
          npm install selenium-webdriver

      - name: Install WGET
        run: | 
          echo "$ apt install wget -y"
          apt install wget -y

      - name: Download Chrome with WGET
        run: |
          echo "$ wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      - name: Install Chrome
        run: |
          echo "$ apt install ./google-chrome-stable_current_amd64.deb"
          apt install ./google-chrome-stable_current_amd64.deb -y 

      - name: Install Chrome Driver
        run: |
          echo "$ apt install chromium-driver -y"
          apt install chromium-driver -y

          echo "$ whereis chromedriver"
          whereis chromedriver

      - name: Check out repository
        uses: actions/checkout@v2

          

      - name : Start Python's HTTP Server run the slenium test
        run: | 
          echo "$ python3 -m http.server"
          python3 -m http.server --bind 127.0.0.1 --directory "../../" & cd src/test/ &&
          node webdriverTest.spec.js